### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JeremiahVaughan** [JeremiahVaughan/simple-chat-gpt#4]
When clearing a long chat and then entering a new question into the prompt, this error appears:

Caught panic:

runtime error: index out of range [-1]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        C:/Users/piega/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.windows-amd64/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        C:/Users/piega/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.windows-amd64/src/runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc00009e500)
        C:/Users/piega/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:705 +0x8b
panic({0x965480?, 0xc000448090?})
        C:/Users/piega/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.windows-amd64/src/runtime/panic.go:785 +0x132
main.model.Update({{0xcc2520, 0x0, 0x0}, {0xcc2520, 0x0, 0x0}, {0xcc2520, 0x0, 0x0}, 0x1, ...}, ...)
        C:/Users/piega/go/pkg/mod/github.com/!jeremiah!vaughan/simple-chat-gpt@v1.2.1/update.go:148 +0x1f86
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00009e500, {0xa32870?, 0xc000132008?}, 0xc0000882a0)
        C:/Users/piega/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:461 +0x7f0
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00009e500)
        C:/Users/piega/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/tea.go:595 +0xacd
main.main()
        C:/Users/piega/go/pkg/mod/github.com/!jeremiah!vaughan/simple-chat-gpt@v1.2.1/main.go:37 +0xd5

[Process exited 0]

**Comment by JeremiahVaughan** [comment]
it was due to a race condition issue after I added in the window to allow multiple lines to be pasted without triggering the send.
